---
- name: install elk stack and beats on any server
  hosts: localhost
  become: true
  roles:
    - pre-requisites
    - elasticsearch
    - kibana
    - filebeat
    - logstash
  vars_files: 
    - vars.yml